project:
  output-dir: output
  # pre-render: [_scripts/convert.bat _stats.ipynb]
  # post-render: [_scripts/rename.py]

bibliography: [references.json]

filters:
  - latex-environment
  - _scripts/filters.lua

commands: [hl]

execute:
  freeze: auto
  cache: refresh
  include: false
  echo: false
  output: false
  message: false
  enabled: true
